samba-client
cifs-utils
python-setuptools
archipel-agent
archipel-agent-action-scheduler
archipel-agent-hypervisor-geolocalization
archipel-agent-hypervisor-health
archipel-agent-hypervisor-network
archipel-agent-hypervisor-platformrequest
archipel-agent-iphone-notification
archipel-agent-virtualmachine-oomkiller
archipel-agent-virtualmachine-snapshoting
archipel-agent-virtualmachine-storage
archipel-agent-virtualmachine-vnc
archipel-agent-vmcasting
archipel-agent-vmparking
archipel-agent-xmppserver
