#!/bin/bash
#
# Create an Ovirt Host USB device (stateless)
# Copyright 2008 Red Hat, Inc.
# Written by Chris Lalancette <clalance@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

ME=$(basename "$0")
warn() { printf "$ME: $@\n" >&2; }
die() { warn "$@"; exit 1; }

test $# != 2 && die "Usage: $ME <usbdevice> <iso-image>"

USBDEVICE=$1
ISO=$2

test ! -r $ISO && die "$ISO is not a readable file"
test ! -b $USBDEVICE && die "$USBDEVICE is not a valid block device"
test $( id -u ) -ne 0 && die "$ME must run as root"

# clear out the old partition table
dd if=/dev/zero of=$USBDEVICE bs=4096 count=1
printf 'n\np\n1\n\n\nt\n6\na\n1\nw\n' | fdisk $USBDEVICE
mkdosfs -n ovirt ${USBDEVICE}1
cat /usr/lib/syslinux/mbr.bin > $USBDEVICE
livecd-iso-to-disk $ISO ${USBDEVICE}1
