#!/bin/bash
#
# Create an Ovirt Host LiveCD
# Copyright 2008 Red Hat, Inc.
# Written by Chris Lalancette <clalance@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

PATH=/sbin:/bin:/usr/bin

KICKSTART=ovirt.ks
CACHE=
if [ -n "$1" ]; then
  CACHE=--cache=$1
fi

LABEL=ovirt-`date +%Y%m%d%H%M`
livecd-creator $CACHE --skip-minimize -c $KICKSTART -f $LABEL 1>&2 &&

echo $LABEL.iso > iso-file
