#!/bin/bash
#
# ovirt Start ovirt services
#
# chkconfig: 3 98 02
# description: ovirt-post services
#

# Source functions library
. /etc/init.d/functions
. /etc/init.d/ovirt-functions

start() {
    find_srv identify tcp
    UUID=`hal-get-property --udi \
        /org/freedesktop/Hal/devices/computer --key system.hardware.uuid`

    if [ -z $UUID ]; then
        ovirt-identify-node -s $SRV_HOST -p $SRV_PORT
    else
        ovirt-identify-node -s $SRV_HOST -p $SRV_PORT -u $UUID
    fi
}

case "$1" in
    start)
        echo -n $"Starting ovirt-post: "

        {
            start
        } >> $OVIRT_LOGFILE 2>&1

        test $? -eq 0 &&  success || failure
        echo
        ;;
    *)
        echo "Usage: ovirt-post {start}"
        exit 2
esac
