#!/bin/bash
#
#
# ovirt-host-keyadd       startup script for ovirt-host-keyadd
#
# chkconfig: - 97 03
# description:  ovirt-host-keyadd is an essential component of the \
#    ovirt VM manager.
#

DAEMON=/usr/share/ovirt-wui/host-keyadd/host-keyadd.rb

. /etc/init.d/functions

start() {
    echo -n "Starting ovirt-host-keyadd: "
    daemon $DAEMON
    RETVAL=$?
    echo
}

stop() {
    echo -n "Shutting down ovirt-host-keyadd: "
    killproc host-keyadd.rb
    RETVAL=$?
    echo
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    status)
	status $DAEMON
	RETVAL=$?
	;;
    *)
      echo "Usage: ovirt-host-keyadd {start|stop|restart|status}"
      exit 1
  ;;
esac
exit $RETVAL
