#!/bin/bash
#
#
# ovirt-taskomatic       startup script for ovirt-taskomatic
#
# chkconfig: - 97 03
# description: ovirt-taskomatic is an essential component of the \
#    ovirt VM manager.
#

[ -r /etc/sysconfig/ovirt-rails ] && . /etc/sysconfig/ovirt-rails

export RAILS_ENV="${RAILS_ENV:-production}"

DAEMON=/usr/share/ovirt-wui/task-omatic/taskomatic.rb

. /etc/init.d/functions

start() {
    echo -n "Starting ovirt-taskomatic: "
    daemon $DAEMON
    RETVAL=$?
    echo
}

stop() {
    echo -n "Shutting down ovirt-taskomatic: "
    killproc taskomatic.rb
    RETVAL=$?
    echo
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    status)
	status $DAEMON
	RETVAL=$?
	;;
    *)
      echo "Usage: ovirt-taskomatic {start|stop|restart|status}"
      exit 1
  ;;
esac
exit $RETVAL
