#!/bin/bash
#
#
# ovirt-mongrel-rails       startup script for ovirt-mongrel-rails
#
# chkconfig: - 97 03
# description: ovirt-mongrel-rails is an essential component of the \
#    ovirt VM manager.
#

[ -r /etc/sysconfig/ovirt-mongrel-rails ] && . /etc/sysconfig/ovirt-mongrel-rails

OVIRT_DIR="${OVIRT_DIR:-/usr/share/ovirt-wui}"
MONGREL_LOG="${MONGREL_LOG:-/var/log/ovirt-wui/mongrel.log}"
MONGREL_PID="${MONGREL_PID:-/var/run/ovirt-wui/mongrel.pid}"
MONGREL_LOCKFILE="${MONGREL_LOCKFILE:-/var/lock/subsys/ovirt-wui}"
RAILS_ENVIRONMENT="${RAILS_ENVIRONMENT:-production}"
USER="${USER:-ovirt}"
GROUP="${GROUP:-ovirt}"
PREFIX="${PREFIX:-/ovirt}"

MONGREL_PROG=mongrel_rails
ADDR=127.0.0.1
REINDEX_PROG=/usr/sbin/ovirt-reindex-search
RETVAL=0

. /etc/init.d/functions

start() {
    echo -n "Starting ovirt-mongrel-rails: "

    RAILS_ENV=$RAILS_ENVIRONMENT $REINDEX_PROG
    $MONGREL_PROG start -c $OVIRT_DIR -l $MONGREL_LOG -P $MONGREL_PID \
	-a $ADDR -e $RAILS_ENVIRONMENT --user $USER --group $GROUP \
	-d --prefix=$PREFIX
    RETVAL=$?
    if [ $RETVAL -eq 0 ] && touch $MONGREL_LOCKFILE ; then
	echo_success
	echo
    else
	echo_failure
	echo
    fi

}

stop() {
    echo -n "Shutting down ovirt-mongrel-rails: "
    $MONGREL_PROG stop -c $OVIRT_DIR -P $MONGREL_PID
    RETVAL=$?
    if [ $RETVAL -eq 0 ] && rm -f $MONGREL_LOCKFILE ; then
	echo_success
	echo
    else
	echo_failure
	echo
    fi
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    status)
	status $MONGREL_PROG
	RETVAL=$?
	;;
    *)
      echo "Usage: ovirt-mongrel-rails {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL
