#!/bin/bash
#
#
# ovirt-wui       startup script for ovirt-wui
#
# chkconfig: - 97 03
# description: ovirt-wui is the web front end for ovirt.
#              

OVIRT_DIR=/usr/share/ovirt-wui
MONGREL_LOG=/var/log/ovirt-wui/mongrel.log
MONGREL_PID=/var/run/ovirt-wui/mongrel.pid
ADDR=127.0.0.1
RAILS_ENVIRONMENT=production
USER=ovirt
GROUP=ovirt
export RAILS_GEM_VERSION=2.0.1

RETVAL=0

. /etc/init.d/functions

start() {
    echo -n "Starting ovirt-wui: "

    mongrel_rails start -c $OVIRT_DIR -l $MONGREL_LOG -P $MONGREL_PID -a $ADDR -e $RAILS_ENVIRONMENT --user $USER --group $GROUP -d
    RETVAL=$?
    if [ $RETVAL -eq 0 ] && touch /var/lock/subsys/ovirt-wui ; then
	echo_success
	echo
    else
	echo_failure
	echo
    fi

    echo -n "Starting host-keyadd: "
    daemon $OVIRT_DIR/host-keyadd/host-keyadd.rb
    echo

    echo -n "Starting host-browser: "
    daemon $OVIRT_DIR/host-browser/host-browser
    echo

    echo -n "Starting host-status: "
    daemon $OVIRT_DIR/host-status/host-status.rb
    echo

    echo -n "Starting taskomatic: "
    daemon $OVIRT_DIR/task-omatic/taskomatic.rb
    echo
}

stop() {
    echo -n "Shutting down taskomatic: "
    killproc taskomatic.rb
    echo

    echo -n "Shutting down host-status: "
    killproc host-status.rb
    echo

    echo -n "Shutting down host-browser: "
    killproc host-browser
    echo

    echo -n "Shutting down host-keyadd: "
    killproc host-keyadd.rb
    echo

    echo -n "Shutting down ovirt-wui: "
    mongrel_rails stop -c $OVIRT_DIR -P $MONGREL_PID
    RETVAL=$?
    if [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/ovirt-wui ; then
	echo_success
	echo
    else
	echo_failure
	echo
    fi
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    *)
      echo "Usage: ovirt-wui {start|stop|restart}"
      exit 1
  ;;
esac      

exit $RETVAL
