#!/bin/bash
#
#
# ovirt-host-collect       startup script for ovirt-host-collect
#
# chkconfig: - 97 03
# description: ovirt-host-collect is an essential component of the \
#    ovirt VM manager.
#

DAEMON=/usr/share/ovirt-wui/host-collect/host-collect.rb

. /etc/init.d/functions

start() {
    echo -n "Starting ovirt-host-collect: "
    daemon $DAEMON
    RETVAL=$?
    echo
}

stop() {
    echo -n "Shutting down ovirt-host-collect: "
    killproc host-collect.rb
    RETVAL=$?
    echo
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    status)
	status $DAEMON
	RETVAL=$?
	;;
    *)
      echo "Usage: ovirt-host-collect {start|stop|restart|status}"
      exit 1
  ;;
esac
exit $RETVAL
