# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "hosts", :force => true do |t|
    t.column "uuid",      :string
    t.column "num_cpus",  :integer
    t.column "cpu_speed", :integer
    t.column "arch",      :string
    t.column "memory",    :integer
  end

  create_table "hosts_storage_volumes", :id => false, :force => true do |t|
    t.column "host_id",           :integer, :null => false
    t.column "storage_volume_id", :integer, :null => false
  end

  create_table "nics", :force => true do |t|
    t.column "mac",        :string
    t.column "ip_addr",    :string
    t.column "usage_type", :string
    t.column "bandwidth",  :integer
    t.column "host_id",    :integer, :null => false
  end

  create_table "storage_volumes", :force => true do |t|
    t.column "ip_addr", :string
    t.column "port",    :integer
    t.column "target",  :string
    t.column "lun",     :string
    t.column "type",    :string
    t.column "size",    :integer
    t.column "host_id", :integer, :null => false
  end

  create_table "storage_volumes_vms", :id => false, :force => true do |t|
    t.column "vm_id",             :integer, :null => false
    t.column "storage_volume_id", :integer, :null => false
  end

  create_table "user_quotas", :force => true do |t|
    t.column "user_id",       :integer, :null => false
    t.column "total_vcpus",   :integer
    t.column "total_vmemory", :integer
    t.column "total_vnics",   :integer
    t.column "total_storage", :integer
  end

  create_table "users", :force => true do |t|
    t.column "ldap_uid", :string
  end

  create_table "vms", :force => true do |t|
    t.column "uuid",                :string
    t.column "num_vcpus_allocated", :integer
    t.column "num_vcpus_used",      :integer
    t.column "memory_allocated",    :integer
    t.column "memory_used",         :integer
    t.column "vnic_mac_addr",       :string
    t.column "state",               :string
    t.column "host_id",             :integer
    t.column "user_id",             :integer
  end

end
