#!/usr/bin/python

import os, string, re

ipaConfName = '/etc/httpd/conf.d/ipa.conf'
ipaRewriteConfName = '/etc/httpd/conf.d/ipa-rewrite.conf'

# make sure we skip this on subsequent runs of this script
if string.find(file(ipaConfName, 'rb').read(), '<VirtualHost *:8089>') < 0:
    ipaConf = open(ipaConfName, 'r')
    ipaText = ipaConf.readlines()
    ipaConf.close()

    ipaConf2 = open(ipaConfName, 'w')
    print >>ipaConf2, "Listen 8089"
    print >>ipaConf2, "NameVirtualHost *:8089"
    print >>ipaConf2, "<VirtualHost *:8089>"
    for line in ipaText:
        ipaConf2.write(line)
    print >>ipaConf2, "</VirtualHost>"
    ipaConf2.close()

if os.path.isfile(ipaRewriteConfName):
    os.remove(ipaRewriteConfName)
    ipaRewriteConf = open(ipaRewriteConfName, 'w')
    print >>ipaRewriteConf, ""
    ipaRewriteConf.close()

