#!/bin/bash

. /etc/init.d/ovirt-functions

PATH=$PATH:/sbin:/usr/sbin
ME=$(basename "$0")
warn() { printf "$ME: $@\n" >&2; }
die() { warn "$@"; exit 1; }

# first, check to see we are root
if [ $( id -u ) -ne 0 ]; then
    die "Must run as root"
fi

if [ $# -ne 0 ]; then
    echo "Usage: $ME"
    exit 1
fi

if [ ! -d $OVIRT_BACKUP_DIR ]; then
    echo "The oVirt backup directory $OVIRT_BACKUP_DIR doesn't exist; can't"
    echo "uninstall the host"
    exit 2
fi

unbackup_file() {
    # note that $1 will have a / on the front, so we don't need to add our own
    test -f "$OVIRT_BACKUP_DIR$1" && cp -pf "$OVIRT_BACKUP_DIR$1" "$1"
}

chkconfig ovirt-listen-awake off
chkconfig collectd off

unbackup_file /etc/sysconfig/network
unbackup_file /etc/hosts
unbackup_file /etc/sysconfig/libvirtd
unbackup_file /etc/libvirt/qemu.conf
unbackup_file /etc/libvirt/libvirtd.conf
unbackup_file /etc/sasl2/libvirt.conf
unbackup_file /etc/sysconfig/iptables
unbackup_file /etc/krb5.conf
unbackup_file /etc/collectd.conf
unbackup_file /etc/sysconfig/libvirt-qpid
rm -Rf $OVIRT_BACKUP_DIR
