#!/bin/bash
#

. /usr/libexec/ovirt-functions

ME=$(basename "$0")
warn() { printf '%s: %s\n' "$ME" "$*" >&2; }
die() { warn "$*"; exit 1; }

trap '__st=$?; stop_log; exit $__st' 0
trap 'exit $?' 1 2 13 15

RETURN_TO_MENU="Return To Menu"

OPTIONS[${#OPTIONS[*]}]="/var/log/ovirt.log"
OPTIONS[${#OPTIONS[*]}]="/var/log/messages"
OPTIONS[${#OPTIONS[*]}]="/var/log/secure"
OPTIONS[${#OPTIONS[*]}]="$RETURN_TO_MENU"

while true; do
    printf "\nPlease select a log file to view.\n\n"
    PS3="Please select a log to view: "
    select OPTION in "${OPTIONS[@]}"
    do
        case $OPTION in
            "$RETURN_TO_MENU") exit 0;;
            "") break;;
            *)
                if [ -s "$OPTION" ]; then
                    clear
                    less -R "$OPTION"
                    printf "\n\n"
                else
                    printf "$OPTION is empty\n\n"
                fi
                ;;
        esac
    done
done
