#!/bin/bash
#
# Configure snmpd
. /usr/libexec/ovirt-functions

trap '__st=$?; stop_log; exit $__st' 0
trap 'exit $?' 1 2 13 15

warn() { printf '%s\n' "$*" >&2; }

if ! is_local_storage_configured; then
    warn "Local storage must be configured prior to configuring SNMP."
    exit 99
fi

set_password() {
    local password=$1
    local CONF=/var/lib/net-snmp/snmpd.conf
    ovirt_store_config /etc/sysconfig/snmpd /var/lib/net-snmp/ >/dev/null

    service snmpd stop
    # reset snmpd options to defaults, image has "-v" to prevent snmpd start
    sed -c -ie '/^OPTIONS/d' /etc/sysconfig/snmpd
    if [ -e $CONF ]; then
         sed -c -ie '/^createUser root/d' $CONF
    fi
    echo "createUser root SHA $password AES" >> $CONF
    service snmpd start
}

if [[ "$1" == "AUTO" ]]; then
    if [ -n "${OVIRT_SNMP_PASSWORD}" ]; then
        set_password $OVIRT_SNMP_PASSWORD
    fi
else
    while true; do
        printf "\n"
        read -p "Enter password for SNMPv3 USM 'root' user: " -esr
        password1="$REPLY"
        printf "\n"
        read -p "Confirm password: " -esr
        password="$REPLY"
        if [ "$password1" = "$password" ]; then break; fi
    done
    printf "\n"
    if ask_yes_or_no "Enable SNMP agent ([Y]es/[N]o)?"; then
        set_password $password
    fi
    printf "\n"
fi
