#!/usr/bin/env python
"""
The bash logic is:
mount -oremount,rw /run/initramfs/live
mount -obind /run/initramfs/live /boot

dracut -f

pushd /boot
  mv -v initrd0.img initrd0.img.orig
  mv -v initramfs-* initrd0.img
popd

umount /boot
mount -oremount,ro /run/initramfs/live
"""

import sys
import logging

# We need to do the log configuration so early, because
# in 3.5, the logging is done wrong in ovirt.node.log
logging.basicConfig(level=logging.INFO,
                    format='%(levelname)s - %(message)s')

from ovirt.node.utils import system


if __name__ == "__main__":
    log = logging.getLogger()

    initramfs = system.Initramfs()
    try:
        kver = check_output(["uname", "-r"])
        initramfs.rebuild(kver)
    except:
        log.exception("Initramfs regeneration failed")
        sys.exit(1)

# vim: set sts=4 et:
