#!/bin/bash
#
# Entry point for configuring an oVirt node when running in standalone mode.

NETWORK="Networking Setup"
STORAGE="Disk Partitioning"
LOGGING="Logging Setup"
PASSWORD="Administrator Password"
CONTINUE="Continue"

declare -a OPTIONS

OPTIONS[${#OPTIONS[*]}]="$NETWORK"
OPTIONS[${#OPTIONS[*]}]="$STORAGE"
OPTIONS[${#OPTIONS[*]}]="$LOGGING"
OPTIONS[${#OPTIONS[*]}]="$PASSWORD"
OPTIONS[${#OPTIONS[*]}]="$CONTINUE"

while true; do
    printf "\n"

    PS3="Please select an option: "

    select OPTION in "${OPTIONS[@]}"
    do
        case "$OPTION" in
            "$NETWORK")  ovirt-config-networking ; break ;;
            "$STORAGE")  ovirt-config-storage    ; break ;;
            "$LOGGING")  ovirt-config-logging    ; break ;;
            "$PASSWORD") ovirt-config-password   ; break ;;
            "$CONTINUE") exit 0 ;;
        esac

        printf "\n"
    done
done
