#!/bin/bash
#
# Wrapper function to make sure the user wishes to continue before
# rebooting the system

. /etc/init.d/ovirt-functions

rc=0
while true; do
    printf "\n\n Local Installation and Reboot\n\n"

    printf "\nThis option will exit the menu, and require a reboot. \n\
Please ensure that you have configured the local storage \n\
and networking correctly on the previous menu before \n\
continuing."
    printf "\n\n"
    bootparams="${OVIRT_BOOTPARAMS}"
    printf "Current kernel boot parameters are:\n"
    printf "${bootparams}\n"
    printf "\n"
    read -p "Please enter kernel boot arguments (hit return to use the above): "
    if [[ -n "$REPLY" ]]; then
	bootparams="${REPLY}"
    else
	bootparams="${OVIRT_BOOTPARAMS}"
    fi
    read -p "Do you wish to continue (Y/n)? "
    r=$(echo $REPLY|tr '[[:lower:]]' '[[:upper:]]')
    if [ "$r" == "Y" ]; then
        mount_live \
        && /usr/sbin/ovirt-config-boot /live "${bootparams}"
        rc=$?
        break
    elif [ "$r" == "N" ]; then
        printf "\nExiting back to the menu\n"
        rc=99
        break
    fi
done
exit $rc
