#!/bin/bash
#
# Entry point for configuring an oVirt node when running in standalone mode.

# symlinked scripts for menu options, link name is menu label
CONFIG_DIR=/etc/ovirt-config-setup.d

# special options, all others execute the symlinked script in CONFIG_DIR
DEBUG_SHELL="Shell"
CONTINUE="Continue Stateless Boot"

declare -a OPTIONS

for cfg in $CONFIG_DIR/*; do
    label=$(basename "$cfg")
    # Assume label is actually XX_Some Text. So strip of the first 3 characters
    label=${label:3}
    OPTIONS[${#OPTIONS[*]}]="$label"
done
OPTIONS[${#OPTIONS[*]}]="$DEBUG_SHELL"
OPTIONS[${#OPTIONS[*]}]="$CONTINUE"


# reset tty, otherwise serial console is broken
reset > /dev/null
clear

while true; do
    printf "\n oVirt Node Standalone Configuration\n\n"

    PS3="Please select an option: "

    select OPTION in "${OPTIONS[@]}"
    do
        case "$OPTION" in
            "$DEBUG_SHELL") bash                 ; break ;;
            "$CONTINUE") exit 0 ;;
            *) $CONFIG_DIR/*"$OPTION" ;;
        esac

        printf "\n"
    done
done
