#!/bin/bash

. /etc/init.d/ovirt-functions

PATH=$PATH:/sbin:/usr/sbin
ME=$(basename "$0")
warn() { printf '%s: %s\n' "$ME" "$*" >&2; }
die() { warn "$@"; exit 1; }

usage() {
    echo "Usage: $ME"
}

# first, check to see we are root
if [ $( id -u ) -ne 0 ]; then
    die "Must run as root"
fi

chkconfig --level 3 ovirt-early on
chkconfig --level 3 ovirt on
chkconfig --level 3 ovirt-post on
chkconfig --level 3 collectd on

ovirt_setup_libvirtd

# make sure we don't autostart virbr0 on libvirtd startup
rm -f /etc/libvirt/qemu/networks/autostart/default.xml

# remove the /etc/krb5.conf file; it will be fetched on bootup
rm -f /etc/krb5.conf

g=$(printf '\33[1m\33[32m')    # similar to g=$(tput bold; tput setaf 2)
n=$(printf '\33[m')            # similar to n=$(tput sgr0)
version=$(rpm -q --qf '%{version}' ovirt-node)
release=$(rpm -q --qf '%{release}' ovirt-node)
cat <<EOF > /etc/issue

           888     888 ${g}d8b$n         888
           888     888 ${g}Y8P$n         888
           888     888             888
   .d88b.  Y88b   d88P 888 888d888 888888
  d88''88b  Y88b d88P  888 888P'   888
  888  888   Y88o88P   888 888     888
  Y88..88P    Y888P    888 888     Y88b.
   'Y88P'      Y8P     888 888      'Y888

  oVirt Node release ${version}-${release}

  Virtualization just got the ${g}Green Light$n

EOF
cp -p /etc/issue /etc/issue.net
