#!/bin/bash
#
# Set the root password and others
# Source functions library
. /etc/init.d/functions
. /etc/init.d/ovirt-functions

trap '__st=$?; stop_log; exit $__st' 0
trap 'exit $?' 1 2 13 15

# Usage: set_sasl_password USER
# Prompt(twice) for a password for the specified USER.
# If they match, set that user's system password,
# and add USER to the SASL list for libvirt.
function set_sasl_password {
    user=$1

    printf "\nNode SASL User ($user):\n"
    saslpasswd2 -a libvirt "$user"
    return 0
}

# Prompts the user for a single username, password combo
function prompt_sasl_user {
    while true; do
        printf "\nPlease enter a new username (hit return to skip) "
        read -e
        test -z "$REPLY" && return 1
        set_sasl_password "$REPLY"
    done
}

printf "\n\n oVirt Node Password Configuration\n\n"

# prompt user
# Set the password for the root user first
printf "\nSystem Administrator (root):\n"
unmount_config /etc/shadow
passwd root
ovirt_store_config /etc/shadow
printf "\nAdding users for libvirt remote access"
# TODO list existing users in /etc/libvirt/passwd.db
while prompt_sasl_user; do :; done
