#!/bin/bash
#
# A wrapper to launch the ovirt-node-setup (configuration) UI
#

reset

python -m ovirt.node.setup.__main__ "$@"

# Get some time to read anything that might appear on the screen
sleep 1
