#!/bin/bash
#
# ovirt Start ovirt services
#
# chkconfig: - 11 99
# description: ovirt services
#

# Source functions library
. /etc/init.d/functions
. /etc/init.d/ovirt-functions

prog=ovirt
lockfile=/var/lock/subsys/$prog

start() {

    touch $lockfile

    if is_standalone; then
        return 0
    fi
    find_srv ipa tcp
    if [ -n "$SRV_HOST" -a -n "$SRV_PORT" ]; then
        krb5_conf=/etc/krb5.conf
        # FIXME this is IPA specific
        wget -q --no-check-certificate \
            http://$SRV_HOST:$SRV_PORT/ipa/config/krb5.ini -O $krb5_conf.tmp
        if [ $? -ne 0 ]; then
            log "Failed to get $krb5_conf"; return 1
        fi
        mv $krb5_conf.tmp $krb5_conf
    else
        log "skipping Kerberos configuration"
    fi

    find_srv identify tcp
    if [ -n "$SRV_HOST" -a -n "$SRV_PORT" ]; then
        krb5_tab=/etc/libvirt/krb5.tab
        # skip ktab download if we got it from /config
        if [ -s $krb5_tab ]; then
          krb5_tab=
        fi
        ovirt-awake start $SRV_HOST $SRV_PORT $krb5_tab
        if [ $? -ne 0 ]; then
            log "ovirt-awake failed"; return 1
        fi
    else
        log "skipping ovirt-awake, oVirt identify service not available"
    fi

    find_srv collectd udp
    if [ -n "$SRV_HOST" -a -n "$SRV_PORT" ]; then
        collectd_conf=/etc/collectd.conf
        if [ -f $collectd_conf.in ]; then
            sed -e "s/@COLLECTD_SERVER@/$SRV_HOST/" \
                -e "s/@COLLECTD_PORT@/$SRV_PORT/" \
                -e "/<Plugin rrdtool>/,/<\/Plugin>/d" $collectd_conf.in \
                > $collectd_conf
            if [ $? -ne 0 ]; then
                log "Failed to write $collectd_conf"; return 1
            fi
        fi
    else
        log "skipping collectd configuration, collectd service not available"
    fi

    find_srv qpidd tcp
    if [ -n "$SRV_HOST" -a -n "$SRV_PORT" ]; then
        libvirt_qpid_conf=/etc/sysconfig/libvirt-qpid
        if [ -f $libvirt_qpid_conf ]; then
            echo "LIBVIRT_QPID_ARGS=\"--broker $SRV_HOST --port $SRV_PORT\"" >> $libvirt_qpid_conf
            echo "/usr/kerberos/bin/kinit -k -t /etc/libvirt/krb5.tab qpidd/`hostname`" >> $libvirt_qpid_conf
        fi
	matahari_conf=/etc/sysconfig/matahari
        if [ -f $matahari_conf ]; then
            echo "MATAHARI_ARGS=\"--broker $SRV_HOST --port $SRV_PORT\"" >> $matahari_conf
            echo "/usr/kerberos/bin/kinit -k -t /etc/libvirt/krb5.tab qpidd/`hostname`" >> $matahari_conf
        fi
    else
        log "skipping libvirt-qpid and matahari configuration, could not find $libvirt_qpid_conf"
    fi

    rm -f $lockfile
}

case "$1" in
    start)
        printf "Starting ovirt: "

        {
            log "Starting ovirt"
            start
            log "Completed ovirt"
        } >> $OVIRT_LOGFILE 2>&1

        test $? == 0 && success || failure
        echo
        ;;
    status)
        status $prog
        ;;
    reload)
        stop
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo "Usage: ovirt {start}"
        exit 2
esac
