#!/bin/bash
#
# ovirt Start ovirt services
#
# chkconfig: - 98 02
# description: ovirt-post services
#

# Source functions library
. /etc/init.d/functions
. /etc/init.d/ovirt-functions

start() {
    # persist selected configuration files
    ovirt_store_config \
      /etc/krb5.conf \
      /etc/libvirt/krb5.tab \
      /etc/ssh/ssh_host*_key*

    if is_standalone; then
        exit 0
    fi
    find_srv identify tcp
    if [ -n "$SRV_HOST" -a -n "$SRV_PORT" ]; then
        ovirt-identify-node -s $SRV_HOST -p $SRV_PORT
    else
        echo "skipping ovirt-identify-node, oVirt registration service not available"
    fi
}

case "$1" in
    start)
        printf "Starting ovirt-post: "

        {
            start
        } >> $OVIRT_LOGFILE 2>&1

        test $? == 0 && success || failure
        echo
        ;;
    *)
        echo "Usage: ovirt-post {start}"
        exit 2
esac
