#!/bin/bash
#
# ovirt Start ovirt services
#
# chkconfig: - 98 02
# description: ovirt-post services
#

# Source functions library
. /etc/init.d/functions
. /etc/init.d/ovirt-functions

start() {
    # wait for libvirt to finish initializing
    local count=0
    while true; do
	if [ -r /var/run/libvirt/libvirt-sock ]; then
	    break
	elif [ "$count" == "100" ]; then
	    log "Libvirt did not initialize in time..."
	    return 1
	else
	    log "Waiting for libvirt to finish initializing..."
	    count=$(expr $count + 1)
	    sleep 1
	fi
    done
    BACKUP=$(mktemp)
    ISSUE=/etc/issue
    ISSUE_NET=/etc/issue.net
    egrep -v "[Vv]irtualization hardware" $ISSUE > $BACKUP
    cp -f $BACKUP $ISSUE
    hwvirt=$(virsh capabilities)
    if [[ $hwvirt =~ kvm ]]; then
	log "Hardware virtualization detected"
    else
	log "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	log "!!! Hardware Virtualization Is Unavailable !!!"
	log "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

	echo "Virtualization hardware is unavailable." >> $ISSUE

	flags=$(cat /proc/cpuinfo | grep "^flags")
	if [[ $flags =~ vmx ]] || [[ $flags =~ svm ]]; then
	    echo "(Virtualization hardware was detected but is disabled)" >> $ISSUE
	else
	    echo "(No virtualization hardware was detected on this system)" >> $ISSUE
	fi
    fi
    cp -f $ISSUE $ISSUE_NET

    if is_standalone; then
        return 0
    fi

    # persist selected configuration files
    ovirt_store_config \
        /etc/krb5.conf \
        /etc/libvirt/krb5.tab \
        /etc/ssh/ssh_host*_key*

    # Removed ovirt-identify-node since it has now
    # been replaced with the matahari qmf agent.
}

case "$1" in
    start)
        printf "Starting ovirt-post: "

        {
            log "Starting ovirt-post"
            start
            log "Completed ovirt-post"
        } >> $OVIRT_LOGFILE 2>&1

        test $? == 0 && success || failure
        echo
        ;;
    *)
        echo "Usage: ovirt-post {start}"
        exit 2
esac
