#!/bin/bash
#
# Copyright (C) 2009, Red Hat, Inc.
# Written by Darryl L. Pierce <dpierce@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.  A copy of the GNU General Public License is
# also available at http://www.gnu.org/copyleft/gpl.html.
#
# Convenience wrapper to give access to the ovirt_store_config
# function in /usr/libexec/ovirt-functions

. /usr/libexec/ovirt-functions

ME=$(basename "$0")
warn() { printf '%s: %s\n' "$ME" "$*" >&2; }
help() { printf "Usage: $ME FILE ...\n
Copies the specified file to /config and then bindmounts it back at it's original location.
The file is stored with its full path detail.\n\n" >&2; exit 1;
}
die() { warn "$*"; help; exit 1; }

if [ $# -eq 0 ]; then die "You need to specify at least one file."; fi

ovirt_store_config $*

