#!/usr/bin/env python2
#
# Copyright (C) 2014, Red Hat, Inc.
# Written by Antoni Segura Puimedon <asegurap@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.  A copy of the GNU General Public License is
# also available at http://www.gnu.org/copyleft/gpl.html.
#
# Convenience wrapper to give access to ovirt/node/utils/fs persistence
# facilities
import argparse
import os
import sys

from ovirt.node.utils import fs


def unpersist():
    parser = argparse.ArgumentParser(
        description="Unpersists a previously persisted path, removing it from "
        "/config. The persisted path is restored to its original location.")
    parser.add_argument('PATH', nargs='+')
    arguments = parser.parse_args(sys.argv[1:])

    conf = fs.Config()
    for path in arguments.PATH:
        if not conf.exists(path):
            print "File not explicitly persisted: %s" % path
            continue

        ret_unpersist = conf.unpersist(path)
        if ret_unpersist == -1:
            print "Cannot unpersist: %s" % path
            return -1

        print "%s successully unpersisted" % path

    return 0

if __name__ == '__main__':
    sys.exit(unpersist())
