#!/bin/bash
#
# Script to install/update a livecd with a set of RPMS provided in a directory
# Copyright 2009 Red Hat, Inc.
# Written by Perry Myers <pmyers@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

if [[ $# < 1 ]]; then
    echo "Usage: $0 rpmdir"
    exit 1
fi

RPMDIR=$1

rpm --root $PWD -Uvh $(find $RPMDIR -type f -name "*.rpm" -print)

