#!/bin/bash
#
# testable-node Copyright (C) 2012 Red Hat, Inc.
# Written by Fabian Deutsch <fabiand@fedoraproject.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.  A copy of the GNU General Public License is
# also available at http://www.gnu.org/copyleft/gpl.html.

isoname=""
verbose=""
reponame=""
dry=false

IGORPLUGIN=ovirt-node-plugin-igor-slave


show_usage()
{
    echo "Usage: $0 [-vd] [-r <.repo-file>] -i <isoname>"
    echo " -i    ISO file to be edited"
    echo " -v    Be verbose"
    echo " -r    Additional .repo file"
    echo " -d    Dry - don't execute edit-node"
    echo ""
    echo "$0 can be used to add the $IGORPLUGIN to a "
    echo "given ISO so it can be tested within an igor setup."
    echo ""
}

die()
{
    echo -e "\nERROR: $@\n" >&2
    show_usage
    exit 1
}

log()
{
    echo -e "$(date +"%F %T") $@"
}

_parse_opts()
{
    log "Parsing args: $@"
    while getopts "h?vdi:r:" opt;
    do
        case "$opt" in
        h|\?)
            show_usage
            exit 0
            ;;
        v)  verbose="-v -d"
            ;;
        i)  isoname=$OPTARG
            ;;
        r)  reponame=$OPTARG
            ;;
        d)  dry=true
            ;;
        esac
    done

    [[ -e "$isoname" ]] || die "<isoname> is missing or does not exist"

    shift $((OPTIND-1))

    [[ "$1" = "--" ]] && shift
}

main()
{
    TMPREPO=igor.repo

    _parse_opts "$@"

    log "Generating temporary repository file: $TMPREPO"
    cmds="s/^\[/\[igor-/ ; /^mirrorlist/d ; s/^#base/base/ ; s/https:/http:/"
    sed "$cmds" /etc/yum.repos.d/*.repo $reponame > $TMPREPO

    ARGS="$verbose "
    ARGS+="--repo $TMPREPO "
    ARGS+="--install $IGORPLUGIN "
    ARGS+="--nogpgcheck "
    ARGS+="$isoname"

    log "Launching edit-node $ARGS"
    log "Dry: $dry"
    $dry || ./edit-node $ARGS

    # Keep temporary repo when in verbose mode
    [[ "$verbose" ]] || unlink $TMPREPO

    log "Done"
}

main "$@"