#!/bin/bash
#
# testable-node Copyright (C) 2012 Red Hat, Inc.
# Written by Fabian Deutsch <fabiand@fedoraproject.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.  A copy of the GNU General Public License is
# also available at http://www.gnu.org/copyleft/gpl.html.

isoname=""
verbose=""
reponame=""

IGORPLUGIN=ovirt-node-plugin-igor-slave



show_usage()
{
    echo "Usage: $0 [-v] [-r <.repo-file>] -i <isoname>"
    echo " -i    ISO file to be edited"
    echo " -v    Be verbose"
    echo " -r    Additional .repo file"
    echo ""
    echo "$0 can be used to add the $IGORPLUGIN to a "
    echo "given ISO so it can be tested within an igor setup."
    echo ""
}

die()
{
    echo -e "\nERROR: $@\n" >&2
    show_usage
    exit 1
}

_parse_opts()
{
    while getopts "h?vi:r:" opt;
    do
        case "$opt" in
        h|\?)
            show_usage
            exit 0
            ;;
        v)  verbose="-v -d"
            ;;
        i)  isoname=$OPTARG
            ;;
        r)  reponame=$OPTARG
            ;;
        esac
    done

    [[ -z "$ISONAME" ]] && die "<isoname> is missing"

    shift $((OPTIND-1))

    [[ "$1" = "--" ]] && shift
}

main()
{
    TMPREPO=igor.repo

    _parse_opts

    cmds="s/^\[/\[igor-/ ; /^mirrorlist/d ; s/^#base/base/ ; s/https:/http:/"
    sed "$cmds" /etc/yum.repos.d/*.repo > $TMPREPO

    [[ ! -z "$reponame" ]] && cat "$reponame" >> $TMPREPO

    ./edit-node $verbose \
      --repo $TMPREPO \
      --install $IGORPLUGIN \
      --nogpgcheck \
      "$isoname"

    unlink $TMPREPO
}

main