#!/usr/bin/ruby

$: << File.join(File.dirname(__FILE__), '../dutils')

require 'active_record_env'

# Get configuration options...
ldap_config = YAML::load(File.open("#{OVIRT_DIR}/config/ldap.yml"))
uid = ARGV[0]
base, host = ldap_config["production"]["base"], ldap_config["production"]["host"]

ActiveLdap::Base.establish_connection :base => base, :host => host, :try_sasl => false

if Account.exists?("uid=#{uid}")
  puts "Creating an admin account for #{uid}..."
  $hwpool = HardwarePool.get_default_pool
  permission = Permission.create(:user_role => Permission::ROLE_SUPER_ADMIN,
				 :uid       => uid,
				 :pool_id   => $hwpool.id)
else
  puts "Unable to verify user: uid=#{uid}"
end
