#!/usr/bin/ruby

$: << File.join(File.dirname(__FILE__), "../dutils")

require 'active_record_env'

$hwpool = HardwarePool.get_default_pool
if $hwpool
  Permission.new( { :role => Permission::ROLE_SUPER_ADMIN,
                    :user => ARGV[0],
                    :pool_id => $hwpool.id}).save
end
